##
# 服务器配置
##
server:
  # 监听端口
  port: 9000
  servlet:
    session:
      # session过期时间
      timeout: 300m

##
# spring配置
##
spring:

  # 模板引擎配置
  thymeleaf:
    # 模板根目录
    prefix: classpath:/templates/
    # 检查模板位置是否存在
    check-template-location: true
    # 给URL后面后缀
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 模板模式
    mode: HTML5
  servlet:
    multipart:
      # 设置最大上传文件大小
      max-request-size: 500MB
      max-file-size: 500MB

  # jackson序列化和反序列化json配置
  jackson:
    #    ##设置json的默认时间转换格式
    #    date-format: yyyy-MM-dd HH:mm:ss

    # 时区
    time-zone: GMT+8
    # null值字段直接不包含在json字符串中
    default-property-inclusion: non_null
    # 序列化配置
    serialization:
      # 设置json中以时间戳形式输出时间
      WRITE_DATES_AS_TIMESTAMPS: true
      # 设置bigDecimal禁用科学计数法
      WRITE_BIGDECIMAL_AS_PLAIN: true
    # 反序列化配置
    deserialization:
      # 使用bigDecimal处理浮点数，防止精度丢失
      USE_BIG_DECIMAL_FOR_FLOATS: true

##
# mybatis配置
##
mybatis:
  # mapper地址配置
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # 自动开启驼峰转换
    map-underscore-to-camel-case: true

##
# 通用mapper
##
mapper:
  style: normal
  mappers:
    - cn.kqk.common.mapper.BaseMapper
  not-empty: false
  identity: MYSQL
  checkExampleEntityClass: true

##
# 分页插件
##
pagehelper:
  # 设置数据方言，如果不设置会自动检测
  helperDialect: mysql
  # 该参数对使用 RowBounds 作为分页参数时有效
  # 当该参数设置为 true 时，会将 RowBounds 中的 offset 参数当成 pageNum 使用，可以用页码和页面大小两个参数进行分页
  offsetAsPageNum: true
  # 该参数对使用 RowBounds 作为分页参数时有效
  # 当该参数设置为true时，使用 RowBounds 分页会进行 count 查询
  rowBoundsWithCount: true
  # 当该参数设置为 true 时
  # 如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果
  #（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  pageSizeZero: true
  # 分页合理化参数，当该参数设置为 true 时
  # pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  # 分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  supportMethodsArguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
